print("Hello Git!")
print("I am learning Git and GitHub")
print("This is my third line")
print("I understand Git!")
print("Calculator feature is being developed")
print("Git branches are extremely useful!")
print("This change was made on GitHub")
print("User profile feature is being developed")
